version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: trello_clon
    env_file: .env   
    ports:
      - "5432:5432"
    volumes:
      - trello_clon:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  trello_clon:
